### ISSUE TITLE
Druid collector is missing DataEntityGroup

### ISSUE THREAD

**Issue by ArtyomyuS** [opendatadiscovery/odd-collector#161]
The current druid collector implementation is missing `DataEntityGroup` group.
This is preventing us from fetching existing datasource`/ingestion/entities/degs/children?oddrn=` endpoint.

**Comment by DementevNikita** [comment]
hey @ArtyomyuS, thanks for opening this!

@Vixtir FYI

**Comment by ArtyomyuS** [comment]
Added this pull request: https://github.com/opendatadiscovery/odd-collector/pull/162
