### ISSUE TITLE
hive collector dose not support iceberg type table 

### ISSUE THREAD

**Issue by lordk911** [opendatadiscovery/odd-collector#173]
`WARNING  | odd_collector.adapters.hive.client:get_all_tables:81 - Unsupported table: Table(tableName='iceberg1', dbName='test', owner='bigtop', createTime=1678353126, lastAccessTime=-979086, retention=2147483647, sd=StorageDescriptor(cols=[FieldSchema(name='id', type='bigint', comment=None), FieldSchema(name='data', type='string', comment=None)], location='hdfs://nsdev/warehouse/tablespace/managed/hive/test.db/iceberg1', inputFormat='org.apache.hadoop.mapred.FileInputFormat', outputFormat='org.apache.hadoop.mapred.FileOutputFormat', compressed=False, numBuckets=0, serdeInfo=SerDeInfo(name=None, serializationLib='org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe', parameters={}, description=None, serializerClass=None, deserializerClass=None, serdeType=None), bucketCols=[], sortCols=[], parameters={}, skewedInfo=SkewedInfo(skewedColNames=[], skewedColValues=[], skewedColValueLocationMaps={}), storedAsSubDirectories=False), partitionKeys=[], parameters={'owner': 'bigtop', 'previous_metadata_location': 'hdfs://nsdev/warehouse/tablespace/managed/hive/test.db/iceberg1/metadata/00001-62fdf41b-0951-4bec-9ad5-e51b6a1322ce.metadata.json', 'current-snapshot-id': '4102097896094370172', 'numRows': '4', 'current-schema': '{"type":"struct","schema-id":0,"fields":[{"id":1,"name":"id","required":false,"type":"long"},{"id":2,"name":"data","required":false,"type":"string"}]}', 'transient_lastDdlTime': '1678353126', 'uuid': '0f46df13-cc45-43bf-be86-fc783e2821b2', 'totalSize': '1306', 'EXTERNAL': 'TRUE', 'current-snapshot-timestamp-ms': '1678353205994', 'numFiles': '2', 'metadata_location': 'hdfs://nsdev/warehouse/tablespace/managed/hive/test.db/iceberg1/metadata/00002-b4c479f4-5296-43b5-b802-8cb771629c1b.metadata.json', 'snapshot-count': '2', 'current-snapshot-summary': '{"spark.app.id":"application_1670566403147_0119","added-data-files":"1","deleted-data-files":"2","added-records":"3","deleted-records":"2","added-files-size":"663","removed-files-size":"1286","changed-partition-count":"1","total-records":"4","total-files-size":"1306","total-data-files":"2","total-delete-files":"0","total-position-deletes":"0","total-equality-deletes":"0"}', 'table_type': 'ICEBERG'}, viewOriginalText=None, viewExpandedText=None, tableType='EXTERNAL_TABLE', privileges=None, temporary=False, rewriteEnabled=False, creationMetadata=None, catName='hive', ownerType=1)`

**Comment by Vixtir** [comment]
Hi, @lordk911 Thanks for reporting. Will be fixed with #174

**Comment by Vixtir** [comment]
Close as solved in #174
