### ISSUE TITLE
[Elasticsearch] Missing Data Streams

### ISSUE THREAD

**Issue by rafiwicht** [opendatadiscovery/odd-collector#175]
I'm currently validating the product to use internally. Quite a lot of data is organized in Elastic Data Streams. As I read in the plugin, you only collect index information, but exclude any data stream indices. Could that be an extension for the adapter?

Additionally I think it would help to move to Python client version 8 and improve authentication options.

If we decide to use it, I might consider a contribution, but I can't promise.

**Comment by Vixtir** [comment]
Hi @rafiwicht ! I'm really sorry for delay! Thank you for that feature request, didn't think about DataStreams, looks interesting!

Elastic now on the way to be refactored, same time we will update client and add fetching streams!

**Comment by Vixtir** [comment]
Hi, @rafiwicht ! We have started investigation Data Streams implementations. I would say that the most interesting part would be to parse metrics from data sources.

Could you please clarify what kind of metadata do you interested in from Elastic Data Streams and describe your use case?

**Comment by rafiwicht** [comment]
Hi @Vixtir 

Sorry for my delay, I was on holidays this week. We want to document, which kind of data is on our Elastic Index, which are organized using Data Streams. I think the best way is to do it is to add the schema from the index templates.

They added the support of component templates, so to get the full index template you need to simulate the index template using the [Simulate index API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-simulate-index.html). 

For our case it is not important to know, what kind of Data Streams uses this index template. This could be a good addition, but I'm not sure how to handle it. Because data streams are normally organized using namespaces (a suffix). I don't know if you want a separate data set for every data stream and then use the index template used by it.

**Comment by Vixtir** [comment]
@rafiwicht Thanks for an answer! Looks interesting! Need a time to investigate Simulate index API

**Comment by rafiwicht** [comment]
@Vixtir If you need some help or any tips, just write here in the issue. I'm happy to help.
