### ISSUE TITLE
Error with Collector adapter to Oracle 19c

### ISSUE THREAD

**Issue by thiagopirex** [opendatadiscovery/odd-collector#177]
I'm trying to run collector for oracle but it's giving the error below:

sqlalchemy.exc.NotSupportedError: (oracledb.exceptions.NotSupportedError) DPY-3015: password verifier type 0x939 is not supported by python-oracledb in thin mode

**Comment by Vixtir** [comment]
Hi, @thiagopirex , thank you for issue! Will take a look!

**Comment by Vixtir** [comment]
Closed with #178
