### ISSUE TITLE
MSSQL Collector

### ISSUE THREAD

**Issue by cgustavoof** [opendatadiscovery/odd-collector#209]
Hi, I've discovered a bug in the `get_columns` function located at `odd-collector/odd_collector/adapters/mssql/repository.py`. The query is causing an 'ambiguous column name in SQL' error. To address this, I suggest modifying the `COLUMNS_QUERY` by including the appropriate alias in the `ORDER BY` clause. Could you guide me on the process to make this correction myself? Thanks.

**Comment by Vixtir** [comment]
Hi, @cgustavoof ! Thanks for using our project!
To correct something by yourself you will need to fork the project first, make changes and open a PR to this repository.
If you want to run collector from src, you will need to use python 3.9.* and `poetry` for managing dependencies. It works as simple as collector docker image, you can config `collector_config.yaml` and run collector (i.e using sh command `sh start.sh`)
Will be happy to help you at any step!

**Comment by Vixtir** [comment]
Could you please provide more information about which mssql release do you use?

**Comment by cgustavoof** [comment]
Microsoft Microsoft SQL Server 2008 R2 (SP3) - 10.50.6220.0 (X64)

**Comment by Vixtir** [comment]
Closed #241.
