### ISSUE TITLE
Error in ClickHouse Collector work

### ISSUE THREAD

**Issue by Aitard** [opendatadiscovery/odd-collector#239]
Hello!

I am trying to deploy ODD on Kubernetes. I have successfully launched odd-platform and odd-collector with configuration for clickhouse. But there are no entities appeared on platform
<img width="1481" alt="image" src="https://github.com/opendatadiscovery/odd-collector/assets/147720498/4f2d4f4c-549c-498b-9645-7f49b3f13e1b">

Also I can see this error in odd-collector pod:
<img width="1359" alt="image" src="https://github.com/opendatadiscovery/odd-collector/assets/147720498/b3acac0d-9a62-409d-8760-ea8286fc1d86">

Could you please clarify, is it bug in odd or have I configured something wrong?

Thank you!

**Comment by Vixtir** [comment]
Hi, @Aitard ! Oh, looks like a problem with parsing datatype as `DateTime64`, i will create a fix in a days!

**Comment by Vixtir** [comment]
Closed in #240
