### ISSUE TITLE
Clickhouse: enhance type mapping

### ISSUE THREAD

**Issue by DementevNikita** [opendatadiscovery/odd-collector#6]
Some of the most common clickhouse types aren't being mapped to the ODD spec.
E.g. IPs, UUIDs, Functional column types

**Comment by Valenzione** [comment]
I'll share a few types we actively use here:

* [UUID](https://clickhouse.com/docs/en/sql-reference/data-types/uuid)
* Aggregating Functions dtypes:
    * [AggregateFunction](https://clickhouse.com/docs/en/sql-reference/data-types/aggregatefunction)
    * [SimpleAggregateFunction](https://clickhouse.com/docs/en/sql-reference/data-types/simpleaggregatefunction)

**Comment by Vixtir** [comment]
Closed in #240
